apiVersion: v1
kind: Service
metadata:
  labels:
    app: guestbook
    tier: frontend
  name: frontend
  namespace: development
spec:
  ports:
  - port: 80
  selector:
    app: guestbook
    tier: frontend
    version: "5"
  type: NodePort
