apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.frontend.name }}"
  labels:
    app: "{{ .Values.frontend.app }}"
    tier: frontend
spec:
  # comment or delete the following line if you want to use a LoadBalancer
  type: {{ .Values.frontend.service.type }}
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  # type: LoadBalancer
  ports:
  - port: {{ .Values.frontend.service.port }}
  selector:
    app: "{{ .Values.frontend.app }}"
    tier: frontend
    version: "4"
