apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.redis.slave.name }}"
  labels:
    app: "{{ .Values.redis.app }}"
    role: slave
    tier: backend
spec:
  ports:
  - port: {{ .Values.redis.slave.service.port }}
  selector:
    app: "{{ .Values.redis.app }}"
    role: slave
    tier: backend
