apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ .Values.redis.slave.name }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Values.redis.app }}"
      role: slave
      tier: backend
  replicas: {{ .Values.redis.slave.replicaCount }}
  template:
    metadata:
      labels:
        app: "{{ .Values.redis.app }}"
        role: slave
        tier: backend
    spec:
      containers:
      - name: slave
        image: "{{ .Values.redis.slave.image.repository }}:{{ .Values.redis.slave.image.tag }}"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
          # If your cluster config does not include a dns service, then to
          # instead access an environment variable to find the master
          # service's host, comment out the 'value: dns' line above, and
          # uncomment the line below:
          # value: env
        ports:
        - containerPort: 6379
