apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.redis.master.name }}"
  labels:
    app: "{{ .Values.redis.app }}"
    role: master
    tier: backend
spec:
  ports:
  - port: {{ .Values.redis.master.service.port }}
    targetPort: 6379
  selector:
    app: redis
    role: master
    tier: backend
